### ISSUE TITLE
Problem with nm-openrc

### ISSUE THREAD

**Issue by aadityabagga** [manjaro/packages-openrc#2] opened 2015-01-24 09:57 UTC
Several people have reported this now...
https://forum.manjaro.org/index.php?topic=19834.msg179471#msg179471
https://forum.manjaro.org/index.php?topic=19793.msg179104#msg179104

All branches are affected I think.

**Comment by udeved** [comment] 2015-01-24 12:49
Resolves itself as soon as NM-1.0.0 is in repos.
It is in testing on arch.

**Comment by aadityabagga** [comment] 2015-01-24 13:56
Thats stupid in my opinion, as people cant update their systems untill NM enters Manjaro.

**Comment by aadityabagga** [comment] 2015-01-24 14:46
@udeved why dont you upload nm-consolekit from the AUR?
https://aur.archlinux.org/packages/networkmanager-consolekit/

**Comment by Kirek** [comment] 2015-01-24 17:40
NetworkManager 1.0 is in unstable now

**Comment by aadityabagga** [comment] 2015-01-24 17:42
Thanks @Kirek maybe @udeved will build and upload networkmanager-consolekit now..

**Comment by udeved** [comment] 2015-01-24 21:58
Ok, will upload nm-ck to unstable.

Had to get a new case and cpu cooling today.

**Comment by udeved** [comment] 2015-01-24 22:03
@aadityabagga 
Stupid is relative, except you wanted to update old nm-openrc, while new nm-ck will use libnm contrary to old nm-openrc. I was simply too lazy to change pkgbuild back to old mechanics for maybe 3 days.

**Comment by manjaro** [comment] 2015-01-24 22:47
I pulled networkmanager 1.0.0 into our repos. Please check again if your commit needs to be reverted.

**Comment by udeved** [comment] 2015-01-24 23:16
Which commit?

I'll update unstable in a minute with rel2 for NM-ck.

**Comment by manjaro** [comment] 2015-01-24 23:18
Forget about it. [here](https://forum.manjaro.org/index.php?topic=19885.0) we go ...

**Comment by manjaro** [comment] 2015-01-24 23:19
If you have still to fix some, please push it to both branches.

**Comment by udeved** [comment] 2015-01-24 23:23
We just need NM-ck in all branches, iirc you did snapshot of the 20140119 builds.

**Comment by manjaro** [comment] 2015-01-24 23:25
Then compile the proper one for current stable or wait till tomorrow when I snap it over. Is rel2 needed in testing or not?

**Comment by udeved** [comment] 2015-01-24 23:30
It depends if you snapshotted nm-openrc-20150119 to testing and stable.

It works properly in unstable now. I just need to know and I should build it for stable and testing too, since nm-openrc depends on nm-ck now.

**Comment by manjaro** [comment] 2015-01-24 23:34
Testing and Unstable have:
<pre>[phil@manjaro testing]$ sudo pacman -Ss networkmanager-openrc
community/networkmanager-openrc 20150124-1 (openrc openrc-misc)</pre>
So is rel2 needed now on those branches or not, as I pushed them both now there ...

**Comment by udeved** [comment] 2015-01-24 23:35
Hang on, I will push rel2 of NM-ck to git.
Haven't done yet.

NM-ck rel2 just fixes and issue rel1 had concerning a fs conflict.

**Comment by udeved** [comment] 2015-01-24 23:39
Yes, we need nm-ck in testing and stable then.
I can build and boxit if you want.

**Comment by manjaro** [comment] 2015-01-24 23:41
Hold on. Testing is now unstable minus linux319. So those two branches are fixed. What is the current issue in stable then? Remember stable has different packages than those other branches.

**Comment by udeved** [comment] 2015-01-24 23:43
The only issue we have/had was that I couldn't build NM-ck which depends on libnm-glib-1.0.0.
This is fixed now when nm came to repos.

We just need to make sure every branch has networkmanager-consolekit.

**Comment by manjaro** [comment] 2015-01-24 23:44
We will when I snap it over to stable by tomorrow. As long as testing and unstable are fixed now it is fine for me. Next time simply hold back those updates. If you need to revert some package in stable to fix it with an older version not creating this issue we can hold back our merge with testing some time to better test KDE changes.

**Comment by udeved** [comment] 2015-01-24 23:50
I dunno. So you snapped nm-ck to testing? According to last boxit memo, you didn't?
I explain quickly, NM-openrc was before 1.0.0 a fully compiled nm replacement.
It has now become just a script provider package which now depends on networkmanager.consolekit.

Networkmanager-consolekit-1.0.0-2 is what we need in testing and stable plus networkmanager-openrc-20150124

**Comment by manjaro** [comment] 2015-01-24 23:52
Then we restore the old package in stable and we are good. Testing and Unstable use NM 1.0.0 and stable will be on 0.9 for some days.

**Comment by manjaro** [comment] 2015-01-24 23:57
so restoring these files will fix stable ?!?

http://mirror.finn.lu/manjaro/pool/overlay/networkmanager-openrc-0.9.10.0-2-i686.pkg.tar.xz
http://mirror.finn.lu/manjaro/pool/overlay/networkmanager-openrc-0.9.10.0-2-i686.pkg.tar.xz.sig
http://mirror.finn.lu/manjaro/pool/overlay/networkmanager-openrc-0.9.10.0-2-x86_64.pkg.tar.xz
http://mirror.finn.lu/manjaro/pool/overlay/networkmanager-openrc-0.9.10.0-2-x86_64.pkg.tar.xz.sig

**Comment by udeved** [comment] 2015-01-25 00:04
yes, if they remove they new nm-openrc-*-any*

**Comment by manjaro** [comment] 2015-01-25 00:16
<pre>### BoxIt memo ###

User philip committed following changes:
 - stable community i686:  1 new and 0 removed package(s)
 - stable community x86_64:  1 new and 0 removed package(s)

stable_community_i686
[New Packages]
networkmanager-openrc-0.9.10.0-2-i686.pkg.tar.xz
stable_community_x86_64
[New Packages]
networkmanager-openrc-0.9.10.0-2-x86_64.pkg.tar.xz</pre>

This should fix it now ...

**Comment by aadityabagga** [comment] 2015-01-25 04:14
God, what an issue...

What I checked on my system that was working:

[networkmanager-consolekit](https://aur.archlinux.org/packages/networkmanager-consolekit/) from the AUR +
[networkmanager-openrc](https://github.com/manjaro/packages-openrc/tree/master/openrc-misc) from the pkgbuilds repo.

Only thing I did not check is the upgrade path from old monolithic networkmanager-openrc to networkmanager-consolekit + networkamanager-openrc (will do this check in a VM now).

**Comment by aadityabagga** [comment] 2015-01-25 04:32
This is the upgrade path from the packages I had built and uploaded to my repo yesterday, seems to work.
```
$ sudo pacman -Syu
:: Synchronizing package databases...
 core                     133.7 KiB   168K/s 00:01 [######################] 100%
 extra                   1909.0 KiB   813K/s 00:02 [######################] 100%
 community                  2.7 MiB   729K/s 00:04 [######################] 100%
 multilib                 137.9 KiB   123K/s 00:01 [######################] 100%
 openrc-eudev is up to date
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Packages (7) libmm-glib-1.4.2-1  libnm-glib-1.0.0-1  mesa-10.4.3-1
             modemmanager-1.4.2-1  networkmanager-consolekit-1.0.0-3
             serf-1.3.8-1  youtube-dl-2015.01.23.4-1

Total Download Size:   11.21 MiB
Total Installed Size:  70.37 MiB
Net Upgrade Size:       9.78 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages ...
 libmm-glib-1.4.2-1-...   291.4 KiB   162K/s 00:02 [######################] 100%
 libnm-glib-1.0.0-1-...   678.2 KiB   470K/s 00:01 [######################] 100%
 mesa-10.4.3-1-x86_64       6.5 MiB   638K/s 00:10 [######################] 100%
 modemmanager-1.4.2-...   848.9 KiB   288K/s 00:03 [######################] 100%
 serf-1.3.8-1-x86_64       53.7 KiB  1342K/s 00:00 [######################] 100%
 networkmanager-cons...     2.0 MiB   788K/s 00:03 [######################] 100%
 youtube-dl-2015.01....   898.7 KiB   643K/s 00:01 [######################] 100%
(7/7) checking keys in keyring                     [######################] 100%
(7/7) checking package integrity                   [######################] 100%
(7/7) loading package files                        [######################] 100%
(7/7) checking for file conflicts                  [######################] 100%
(7/7) checking available disk space                [######################] 100%
(1/7) upgrading libmm-glib                         [######################] 100%
(2/7) upgrading libnm-glib                         [######################] 100%
(3/7) upgrading mesa                               [######################] 100%
(4/7) upgrading modemmanager                       [######################] 100%
(5/7) upgrading networkmanager-consolekit          [######################] 100%
(6/7) upgrading serf                               [######################] 100%
(7/7) upgrading youtube-dl                         [######################] 100%
```

In my opinion for stable we can use nm-consolekit from AUR + nm-openrc from pkgbuilds repo (rather than using older monolithic nm-openrc).

**Comment by aadityabagga** [comment] 2015-01-25 04:42
Another Issue for @udeved 

In post install old networkmanager service will need to be removed (new one is NetworkManager), i will try to do that now in packages-openrc.

**Comment by manjaro** [comment] 2015-01-25 09:19
I still don't get what the issue is here. In stable we have 0.9.10 series and in testing/unstable we updated to 1.0.0. Old networkmanager-openrc got restored to "fix" stable for some days before we merge our current changes to that branch ...

**Comment by aadityabagga** [comment] 2015-01-25 10:31
@manjaro got it.

**Comment by udeved** [comment] 2015-01-25 12:53
So what is the issue aaditya?

**Comment by aadityabagga** [comment] 2015-01-25 12:56
Old nm service was networkmanager, new one is NetworkManager. If you dont remove old service from runlevel, it leads to broken symlink.

Second Philm has explained that when testing syncs with stable, new nm will go in.

**Comment by udeved** [comment] 2015-01-25 12:58
NM-openrc post_install was fixed by yourself, I rebuilt this package yesterday.

**Closed by udeved** 2015-01-25 12:58 UTC
Labels: bug, wontfix
